# $Header: /home/cjm/cvs/ics_gui/Makefile.common,v 1.2 2020-04-29 13:57:42 cjm Exp $

ICS_GUI_HOME		=	ics_gui
ICS_GUI_SRC_HOME	= 	$(LT_SRC_HOME)/$(ICS_GUI_HOME)
ICS_GUI_BIN_HOME	= 	$(LT_BIN_HOME)/$(ICS_GUI_HOME)
ICS_GUI_DOC_HOME	= 	$(LT_DOC_HOME)/$(ICS_GUI_HOME)

#
# $Log: not supported by cvs2svn $
# Revision 1.1  2003/11/14 15:27:19  cjm
# Initial revision
#
#
